<a href="https://colab.research.google.com/github/asenka239/compMath/blob/main/Home_task_%E2%84%961.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
import numpy as np

Задание № 1

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6,]])
b = np.array([[7, 8],
              [9, 10]])

print(a)
print(b)
a_plus_b = np.concatenate([a, b], axis=1)
print(a_plus_b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]]
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


Задание №2

In [ ]:
a = np.arange(5)
b = np.arange(0, 10, 2)
M = np.random.randint(10, size = (max(a)+1, max(b)+1))
print('M = \n', M, '\n')

np.diag(M[a][:, b])

M = 
 [[4 3 6 8 3 5 0 9 2]
 [5 6 5 3 0 4 0 5 9]
 [0 3 7 0 7 2 4 2 3]
 [9 9 8 1 2 5 1 2 2]
 [9 0 0 7 9 6 9 5 1]] 



array([4, 5, 7, 1, 1])

Задание №3

In [ ]:
M = np.array([[6, 2, 1, 2, 9],
              [6, 4, 8, 8, 7],
              [0, 2, 0, 0, 0],
              [6, 6, 6, 3, 2],
              [7, 3, 8, 5, 9]])

print('Trace of M is', M.trace())
print('Diagonal of M has', np.count_nonzero(np.diag(M)))

Trace of M is 22
Diagonal of M has 4


Задание №4

In [ ]:
M = np.random.randint(20, size = (10, 10))
print(M)

np.asarray(np.unique(M, return_counts=True)).T

[[14  5 10  0  5 15 14 14 11 12]
 [16  2  0  4 11 12  8  1 15 15]
 [11 19  3  9  0  4  7  6  5  3]
 [16 16 12 15  5 17  2  4  6 15]
 [14  5  6 11 15  3  6 12 12 10]
 [15  9  3 12  3 12 13  0  2  9]
 [19 14 10 13 18  6 12  1  2 19]
 [ 4 17  6  4  0 17 13  9  4  0]
 [13  0  9  2 15 12  3 14  1  5]
 [ 6 16  6 19  2  0  2 19  3  7]]


array([[ 0,  8],
       [ 1,  3],
       [ 2,  7],
       [ 3,  7],
       [ 4,  6],
       [ 5,  6],
       [ 6,  8],
       [ 7,  2],
       [ 8,  1],
       [ 9,  5],
       [10,  3],
       [11,  4],
       [12,  9],
       [13,  4],
       [14,  6],
       [15,  8],
       [16,  4],
       [17,  3],
       [18,  1],
       [19,  5]])

Задание №5

In [ ]:
 m = 4
 n = 3
 a, b = np.random.randint(-10, high=10, size=(m,n)), np.random.randint(-10, high=10, size=(m,n))
 print('a = \n', a, '\n b = \n', b, '\n')

 b * (np.greater_equal(a, 0))

a = 
 [[  0   7  -5]
 [  4   5  -9]
 [  3   5 -10]
 [  6  -8  -5]] 
 b = 
 [[ 3  3 -6]
 [-6  9 -5]
 [ 3  0  1]
 [-7  6  8]] 



array([[ 3,  3,  0],
       [-6,  9,  0],
       [ 3,  0,  0],
       [-7,  0,  0]])

Задание №6

In [ ]:
M = np.array([[6, 2, 1, 2, 9],
              [6, 4, 8, 8, 7],
              [0, 2, 0, 0, 0],
              [6, 6, 6, 3, 2],
              [7, 3, 8, 5, 9]])

M_ = M - np.mean(M, 0)
print(M_)

M_ / np.linalg.norm(M_, axis=0)

[[ 1.  -1.4 -3.6 -1.6  3.6]
 [ 1.   0.6  3.4  4.4  1.6]
 [-5.  -1.4 -4.6 -3.6 -5.4]
 [ 1.   2.6  1.4 -0.6 -3.4]
 [ 2.  -0.4  3.4  1.4  3.6]]


array([[ 0.1767767 , -0.41833001, -0.46788772, -0.26233033,  0.43276233],
       [ 0.1767767 ,  0.17928429,  0.44189396,  0.72140842,  0.19233881],
       [-0.88388348, -0.41833001, -0.59785653, -0.59024325, -0.6491435 ],
       [ 0.1767767 ,  0.7768986 ,  0.18195634, -0.09837388, -0.40871998],
       [ 0.35355339, -0.11952286,  0.44189396,  0.22953904,  0.43276233]])